### ISSUE TITLE
배포를 위한 mysql 의존성 추가 및 application.properties 세팅

### ISSUE THREAD

**Issue by m1naworld** [m1naworld/hanghae-soribaddah-api#22]
## Description
개발시에도 디비를 하나로 통합하고자 h2가 아닌 mysql을 사용하려고 합니다!
이에 mysql 의존성을 추가하고, application-dev.properties에 db를 세팅하고자합니다.
application-dev.properties와 application-prod.properties는 나중에 슬랙으로 공유하도록 하겠습니다. 

## Todo
- [x] 오라클 클라우드를 통한 인스턴스 생성 
- [x] 배포서버에 mysql 설치 및 root권한 비밀번호 설정 
- [x] 프로젝트에 mysql 설정하기
- [ ] 프로젝트 배포해보기 
- [ ] 프로젝트 배포 확인 테스트

## Etc
기타사항
